### ISSUE TITLE
postmanctl command to export collection and export environment

### ISSUE THREAD

**Issue by duranaustin** [kevinswiber/postmanctl#11]
Hi there, I'm curious if postmanctl has the ability to export collections and export environments--as done on the postman app by right-clicking and selecting "export".

**Comment by duranaustin** [comment]
figured out a different way without using postmanctl.

You can use Postman's API to get a single collection
```
curl --location --request GET 'https://api.getpostman.com/collections/{{collection_uid}}' \
--header 'X-Api-Key: '
```
Or a single env
```
curl --location --request GET 'https://api.getpostman.com/environments/{{environment_uid}}' \
--header 'X-Api-Key: '
```

**Comment by cpoissonnier** [comment]
You still can use postmanctl for this : 

```
postmanctl get collection <collection_uid> -o json
postmanctl get environment <environment_uid> -o json
```
