### ISSUE TITLE
postmanctl get ws $workspace_id -o json does not return the environments as API does

### ISSUE THREAD

**Issue by lolo58200** [kevinswiber/postmanctl#9]
Hi Kevin,
I found out this issue when trying to extend the script to find orphan collections to orphan environments.
rgds
Laurent

**Comment by kevinswiber** [comment]
Hey @lolo58200,

Thanks for reporting this!  The fix has been released in v1.1.5.  If you're using Homebrew, you can just `brew upgrade postmanctl`.  Otherwise, you can download a new version here: https://github.com/kevinswiber/postmanctl/releases/tag/v1.1.5.

Thanks again!

**Comment by lolo58200** [comment]
Hi Kevin, just checked it works fine
thks again
